import type { User, DocumentTemplate, GeneratedDocument, SystemAuditLog } from '../types';

// Helper to generate IDs
const uuid = () => Math.random().toString(36).substring(2, 11);

// Standard seed templates
const SEED_TEMPLATES: DocumentTemplate[] = [
  {
    id: 'psur',
    name: 'PSUR Event Summary',
    description: 'Generates periodic safety update report event summaries with safety risk analysis schemas.',
    supportedFileTypes: ['.xlsx', '.xls'],
    lastUpdated: '2026-06-25T14:32:00Z',
    icon: 'FileText'
  },
  {
    id: 'quant',
    name: 'Quantitative Method (Non-DME)',
    description: 'Processes non-DME safety event data to measure quantitative risk scores and Z-scores.',
    supportedFileTypes: ['.xlsx', '.csv'],
    lastUpdated: '2026-06-28T09:15:00Z',
    icon: 'BarChart3'
  },
  {
    id: 'pv_auto',
    name: 'PV Auto Tool',
    description: 'Automates pharmacovigilance reports compiles signal detection Excel data sets.',
    supportedFileTypes: ['.xlsx'],
    lastUpdated: '2026-06-30T10:00:00Z',
    icon: 'Activity'
  }
];

// Seed users
const SEED_USERS: User[] = [
  {
    id: 'usr-1',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=100&q=80',
    name: 'Sarah Connor',
    email: 'admin@company.com',
    role: 'Admin',
    status: 'Active',
    createdDate: '2026-01-10T08:00:00Z',
    lastLogin: '2026-06-30T12:45:00Z',
    documentsGenerated: 142,
    allowedTemplates: ['psur', 'quant', 'pv_auto']
  },
  {
    id: 'usr-2',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=100&q=80',
    name: 'Alex Mercer',
    email: 'user@company.com',
    role: 'User',
    status: 'Active',
    createdDate: '2026-02-15T09:30:00Z',
    lastLogin: '2026-06-30T11:20:00Z',
    documentsGenerated: 68,
    allowedTemplates: ['psur', 'pv_auto']
  },
  {
    id: 'usr-3',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=100&q=80',
    name: 'Elena Rostova',
    email: 'elena.r@company.com',
    role: 'User',
    status: 'Active',
    createdDate: '2026-03-01T10:15:00Z',
    lastLogin: '2026-06-29T16:40:00Z',
    documentsGenerated: 110,
    allowedTemplates: ['psur', 'quant', 'pv_auto']
  },
  {
    id: 'usr-4',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=100&q=80',
    name: 'Marcus Aurelius',
    email: 'marcus@company.com',
    role: 'User',
    status: 'Inactive',
    createdDate: '2026-03-12T14:22:00Z',
    lastLogin: '2026-06-15T10:05:00Z',
    documentsGenerated: 45,
    allowedTemplates: ['quant']
  },
  {
    id: 'usr-5',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=100&q=80',
    name: 'Linda Croft',
    email: 'linda.c@company.com',
    role: 'User',
    status: 'Active',
    createdDate: '2026-04-05T11:00:00Z',
    lastLogin: '2026-06-30T09:12:00Z',
    documentsGenerated: 24,
    allowedTemplates: ['psur', 'quant']
  },
  {
    id: 'usr-6',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=100&q=80',
    name: 'Chloe Frazer',
    email: 'chloe.f@company.com',
    role: 'User',
    status: 'Active',
    createdDate: '2026-04-18T16:45:00Z',
    lastLogin: '2026-06-28T14:30:00Z',
    documentsGenerated: 89,
    allowedTemplates: ['pv_auto']
  },
  {
    id: 'usr-7',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=100&q=80',
    name: 'Leon Kennedy',
    email: 'leon.k@company.com',
    role: 'User',
    status: 'Inactive',
    createdDate: '2026-05-02T13:10:00Z',
    lastLogin: '2026-06-10T17:15:00Z',
    documentsGenerated: 0,
    allowedTemplates: []
  }
];

// Seed generation history
const SEED_DOCUMENTS: GeneratedDocument[] = [
  {
    id: 'doc-1',
    name: 'PSUR_Summary_Q2_2026_V1',
    templateId: 'psur',
    templateName: 'PSUR Event Summary',
    createdBy: 'Sarah Connor',
    createdById: 'usr-1',
    generatedTime: '2026-06-30T12:05:00Z',
    downloaded: true,
    downloadCount: 3,
    fileSize: 18456,
    reportType: 'PSUR',
    status: 'Success',
    version: '1.0.0',
    excelFileName: 'PSUR_Data_Source_2026_Q2.xlsx',
    htmlContent: `
      <div style="font-family: sans-serif; padding: 24px; color: #1e293b;">
        <h1 style="color: #4f46e5; border-bottom: 2px solid #e2e8f0; padding-bottom: 8px;">Periodic Safety Update Report (PSUR) - Summary</h1>
        <p style="color: #64748b; font-size: 14px;">Generated on: 2026-06-30 12:05:00 UTC | Generated by: Sarah Connor</p>
        
        <div style="margin-top: 24px; background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 16px;">
          <h3 style="margin-top: 0; color: #0f172a;">Executive Analytics</h3>
          <table style="width: 100%; border-collapse: collapse; margin-top: 12px;">
            <thead>
              <tr style="background: #e2e8f0; text-align: left;">
                <th style="padding: 8px; border: 1px solid #cbd5e1;">Metric</th>
                <th style="padding: 8px; border: 1px solid #cbd5e1;">Value</th>
                <th style="padding: 8px; border: 1px solid #cbd5e1;">Risk Level</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td style="padding: 8px; border: 1px solid #cbd5e1;">Total Adverse Events (AE)</td>
                <td style="padding: 8px; border: 1px solid #cbd5e1; font-weight: bold;">1,248</td>
                <td style="padding: 8px; border: 1px solid #cbd5e1; color: #ef4444; font-weight: bold;">HIGH</td>
              </tr>
              <tr style="background: #f1f5f9;">
                <td style="padding: 8px; border: 1px solid #cbd5e1;">Serious Adverse Events (SAE)</td>
                <td style="padding: 8px; border: 1px solid #cbd5e1; font-weight: bold;">142</td>
                <td style="padding: 8px; border: 1px solid #cbd5e1; color: #f59e0b; font-weight: bold;">MEDIUM</td>
              </tr>
              <tr>
                <td style="padding: 8px; border: 1px solid #cbd5e1;">Signal Detection Index</td>
                <td style="padding: 8px; border: 1px solid #cbd5e1; font-weight: bold;">0.84</td>
                <td style="padding: 8px; border: 1px solid #cbd5e1; color: #10b981; font-weight: bold;">NORMAL</td>
              </tr>
            </tbody>
          </table>
        </div>
        
        <div style="margin-top: 24px;">
          <h3 style="color: #0f172a;">Event Type Distribution Analysis</h3>
          <p>The uploaded dataset PSUR_Data_Source_2026_Q2.xlsx contains a total of 1,248 event logs. The analysis detected a 12% rise in cardiovascular markers, which is within the expected seasonal variation index. Safety indicators remain within tolerances.</p>
        </div>
      </div>
    `
  },
  {
    id: 'doc-2',
    name: 'QuantMethod_Beta_Test_V2',
    templateId: 'quant',
    templateName: 'Quantitative Method (Non-DME)',
    createdBy: 'Elena Rostova',
    createdById: 'usr-3',
    generatedTime: '2026-06-29T15:10:00Z',
    downloaded: false,
    downloadCount: 0,
    fileSize: 14210,
    reportType: 'PSUR',
    status: 'Success',
    version: '2.1.0',
    excelFileName: 'Quant_Raw_Metrics_V2.xlsx',
    htmlContent: `
      <div style="font-family: sans-serif; padding: 24px; color: #1e293b;">
        <h1 style="color: #0d9488; border-bottom: 2px solid #e2e8f0; padding-bottom: 8px;">Quantitative Method Safety Metrics</h1>
        <p style="color: #64748b; font-size: 14px;">Generated on: 2026-06-29 15:10:00 UTC | Generated by: Elena Rostova</p>
        
        <div style="margin-top: 24px; background: #f0fdfa; border: 1px solid #ccfbf1; border-radius: 8px; padding: 16px;">
          <h3 style="margin-top: 0; color: #115e59;">Z-Score Analysis Summary</h3>
          <p>Statistical distribution scores of non-DME (Designated Medical Events) cases compiled.</p>
          <table style="width: 100%; border-collapse: collapse; margin-top: 12px;">
            <thead>
              <tr style="background: #ccfbf1; text-align: left; color: #115e59;">
                <th style="padding: 8px; border: 1px solid #99f6e4;">Method ID</th>
                <th style="padding: 8px; border: 1px solid #99f6e4;">Sample Size</th>
                <th style="padding: 8px; border: 1px solid #99f6e4;">Z-Score</th>
                <th style="padding: 8px; border: 1px solid #99f6e4;">P-Value</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td style="padding: 8px; border: 1px solid #99f6e4;">METH-402</td>
                <td style="padding: 8px; border: 1px solid #99f6e4;">12,450</td>
                <td style="padding: 8px; border: 1px solid #99f6e4; font-weight: bold;">+1.98</td>
                <td style="padding: 8px; border: 1px solid #99f6e4; color: #0d9488; font-weight: bold;">0.047 *</td>
              </tr>
              <tr style="background: #fdf2f8;">
                <td style="padding: 8px; border: 1px solid #99f6e4;">METH-409</td>
                <td style="padding: 8px; border: 1px solid #99f6e4;">4,810</td>
                <td style="padding: 8px; border: 1px solid #99f6e4; font-weight: bold; color: #ef4444;">+3.45</td>
                <td style="padding: 8px; border: 1px solid #99f6e4; color: #ef4444; font-weight: bold;">0.001 **</td>
              </tr>
              <tr>
                <td style="padding: 8px; border: 1px solid #99f6e4;">METH-510</td>
                <td style="padding: 8px; border: 1px solid #99f6e4;">8,920</td>
                <td style="padding: 8px; border: 1px solid #99f6e4; font-weight: bold;">-0.42</td>
                <td style="padding: 8px; border: 1px solid #99f6e4;">0.674</td>
              </tr>
            </tbody>
          </table>
          <p style="font-size: 12px; color: #4b5563; margin-top: 12px;">* Statistically significant (p < 0.05) | ** Highly significant (p < 0.01)</p>
        </div>
      </div>
    `
  },
  {
    id: 'doc-3',
    name: 'PV_Auto_Signal_Detection_June_V1',
    templateId: 'pv_auto',
    templateName: 'PV Auto Tool',
    createdBy: 'Alex Mercer',
    createdById: 'usr-2',
    generatedTime: '2026-06-30T11:25:00Z',
    downloaded: true,
    downloadCount: 1,
    fileSize: 15124,
    reportType: 'PSUR',
    status: 'Success',
    version: '1.0.0',
    excelFileName: 'PV_Signal_Inputs_June.xlsx',
    htmlContent: `
      <div style="font-family: sans-serif; padding: 24px; color: #1e293b;">
        <h1 style="color: #8b5cf6; border-bottom: 2px solid #e2e8f0; padding-bottom: 8px;">Pharmacovigilance (PV) Auto Tool Report</h1>
        <p style="color: #64748b; font-size: 14px;">Generated on: 2026-06-30 11:25:00 UTC | Generated by: Alex Mercer</p>
        
        <div style="margin-top: 24px; background: #faf5ff; border: 1px solid #f3e8ff; border-radius: 8px; padding: 16px;">
          <h3 style="margin-top: 0; color: #6b21a8;">Signal Detection Trigger Log</h3>
          <p>Analysis on PV_Signal_Inputs_June.xlsx identified 3 active signals meeting threshold criteria:</p>
          <ul>
            <li><strong>Signal 1: AutoCode-C93</strong> - Priority: High | PRR: 3.42 | Chi-Square: 14.85</li>
            <li><strong>Signal 2: AutoCode-D12</strong> - Priority: Medium | PRR: 2.15 | Chi-Square: 6.92</li>
            <li><strong>Signal 3: AutoCode-A04</strong> - Priority: Low | PRR: 1.54 | Chi-Square: 4.10</li>
          </ul>
        </div>
      </div>
    `
  },
  {
    id: 'doc-4',
    name: 'PV_Auto_Failure_Log',
    templateId: 'pv_auto',
    templateName: 'PV Auto Tool',
    createdBy: 'Chloe Frazer',
    createdById: 'usr-6',
    generatedTime: '2026-06-28T14:28:00Z',
    downloaded: false,
    downloadCount: 0,
    fileSize: 0,
    reportType: 'PSUR',
    status: 'Failed',
    version: '1.0.0',
    excelFileName: 'Corrupt_Data_Format.xlsx',
    failedReason: "SchemaValidationError: Required column 'AutoCode' was missing in file 'Corrupt_Data_Format.xlsx'. Parsed columns were: [ID, EventType, Timestamp, Value].",
    htmlContent: `
      <div style="font-family: sans-serif; padding: 24px; color: #991b1b; background: #fef2f2; border: 1px solid #fee2e2; border-radius: 8px;">
        <h1 style="color: #b91c1c; border-bottom: 2px solid #fecaca; padding-bottom: 8px;">Generation Failure Report</h1>
        <p style="font-size: 14px; color: #7f1d1d;">Failed on: 2026-06-28 14:28:00 UTC | Attempted by: Chloe Frazer</p>
        <div style="margin-top: 16px;">
          <strong>Error Description:</strong>
          <p style="margin-top: 8px; font-family: monospace; background: #ffffff; padding: 12px; border-radius: 4px; border: 1px solid #fca5a5;">
            SchemaValidationError: Required column 'AutoCode' was missing in file 'Corrupt_Data_Format.xlsx'. Parsed columns were: [ID, EventType, Timestamp, Value].
          </p>
        </div>
      </div>
    `
  }
];

// Seed Audit Logs
const SEED_AUDIT_LOGS: SystemAuditLog[] = [
  {
    id: 'log-1',
    timestamp: '2026-06-30T12:45:00Z',
    userId: 'usr-1',
    userName: 'Sarah Connor',
    action: 'USER_LOGIN',
    details: 'Administrator logged in successfully from IP 192.168.1.42.'
  },
  {
    id: 'log-2',
    timestamp: '2026-06-30T12:05:00Z',
    userId: 'usr-1',
    userName: 'Sarah Connor',
    action: 'DOC_GENERATE',
    details: 'Generated document "PSUR_Summary_Q2_2026_V1" from template "PSUR Event Summary".'
  },
  {
    id: 'log-3',
    timestamp: '2026-06-30T11:25:00Z',
    userId: 'usr-2',
    userName: 'Alex Mercer',
    action: 'DOC_GENERATE',
    details: 'Generated document "PV_Auto_Signal_Detection_June_V1" from template "PV Auto Tool".'
  },
  {
    id: 'log-4',
    timestamp: '2026-06-30T11:20:00Z',
    userId: 'usr-2',
    userName: 'Alex Mercer',
    action: 'USER_LOGIN',
    details: 'User logged in successfully from IP 192.168.1.109.'
  },
  {
    id: 'log-5',
    timestamp: '2026-06-30T10:05:00Z',
    userId: 'usr-1',
    userName: 'Sarah Connor',
    action: 'USER_CREATE',
    details: 'Created new user account for Chloe Frazer (chloe.f@company.com).'
  },
  {
    id: 'log-6',
    timestamp: '2026-06-29T16:45:00Z',
    userId: 'usr-1',
    userName: 'Sarah Connor',
    action: 'PERM_CHANGE',
    details: 'Modified permissions for Marcus Aurelius: set status to Inactive.'
  }
];

// Initialize database in localStorage
export const initDb = () => {
  if (!localStorage.getItem('pv_users')) {
    localStorage.setItem('pv_users', JSON.stringify(SEED_USERS));
  }
  if (!localStorage.getItem('pv_templates')) {
    localStorage.setItem('pv_templates', JSON.stringify(SEED_TEMPLATES));
  }
  if (!localStorage.getItem('pv_documents')) {
    localStorage.setItem('pv_documents', JSON.stringify(SEED_DOCUMENTS));
  }
  if (!localStorage.getItem('pv_audit_logs')) {
    localStorage.setItem('pv_audit_logs', JSON.stringify(SEED_AUDIT_LOGS));
  }
};

// Mock API database service
export const mockDb = {
  // USERS
  getUsers: (): User[] => {
    initDb();
    return JSON.parse(localStorage.getItem('pv_users') || '[]');
  },
  saveUser: (user: User): User => {
    initDb();
    const users = mockDb.getUsers();
    const index = users.findIndex(u => u.id === user.id);
    if (index >= 0) {
      users[index] = user;
    } else {
      user.id = `usr-${uuid()}`;
      users.push(user);
    }
    localStorage.setItem('pv_users', JSON.stringify(users));
    return user;
  },
  deleteUser: (userId: string): boolean => {
    initDb();
    const users = mockDb.getUsers();
    const filtered = users.filter(u => u.id !== userId);
    localStorage.setItem('pv_users', JSON.stringify(filtered));
    return true;
  },
  resetPassword: (userId: string): string => {
    initDb();
    // Simulate reset, returns new password
    const password = `Reset_${Math.random().toString(36).substring(2, 8)}!`;
    const users = mockDb.getUsers();
    const user = users.find(u => u.id === userId);
    if (user) {
      // In a real db, we'd hash and store it. Here we just log.
      mockDb.addAuditLog('PASSWORD_RESET', `Admin reset password for user ${user.name} (${user.email}).`, 'usr-1', 'Sarah Connor');
    }
    return password;
  },

  // TEMPLATES
  getTemplates: (): DocumentTemplate[] => {
    initDb();
    return JSON.parse(localStorage.getItem('pv_templates') || '[]');
  },
  saveTemplate: (template: DocumentTemplate): DocumentTemplate => {
    initDb();
    const templates = mockDb.getTemplates();
    const index = templates.findIndex(t => t.id === template.id);
    if (index >= 0) {
      templates[index] = template;
    } else {
      template.id = `tpl-${uuid()}`;
      templates.push(template);
    }
    localStorage.setItem('pv_templates', JSON.stringify(templates));
    return template;
  },

  // DOCUMENTS
  getDocuments: (): GeneratedDocument[] => {
    initDb();
    return JSON.parse(localStorage.getItem('pv_documents') || '[]');
  },
  addDocument: (doc: Omit<GeneratedDocument, 'id' | 'generatedTime' | 'downloaded' | 'version'>): GeneratedDocument => {
    initDb();
    const documents = mockDb.getDocuments();
    const users = mockDb.getUsers();

    // Increment document count for creator
    const creator = users.find(u => u.id === doc.createdById || u.name === doc.createdBy);
    if (creator) {
      creator.documentsGenerated += 1;
      mockDb.saveUser(creator);
    }

    const newDoc: GeneratedDocument = {
      ...doc,
      id: `doc-${uuid()}`,
      generatedTime: new Date().toISOString(),
      downloaded: false,
      version: '1.0.0'
    };
    
    documents.unshift(newDoc); // Add to top of list
    localStorage.setItem('pv_documents', JSON.stringify(documents));
    
    mockDb.addAuditLog(
      newDoc.status === 'Success' ? 'DOC_GENERATE' : 'DOC_GENERATE_FAIL', 
      `User ${newDoc.createdBy} attempted report generation for ${newDoc.templateName} using file ${newDoc.excelFileName}. Status: ${newDoc.status}`,
      newDoc.createdById,
      newDoc.createdBy
    );

    return newDoc;
  },
  deleteDocument: (docId: string): boolean => {
    initDb();
    const documents = mockDb.getDocuments();
    const filtered = documents.filter(d => d.id !== docId);
    localStorage.setItem('pv_documents', JSON.stringify(filtered));
    return true;
  },
  toggleDownloaded: (docId: string): void => {
    initDb();
    const documents = mockDb.getDocuments();
    const doc = documents.find(d => d.id === docId);
    if (doc) {
      doc.downloaded = true;
      localStorage.setItem('pv_documents', JSON.stringify(documents));
      
      mockDb.addAuditLog(
        'DOC_DOWNLOAD', 
        `Downloaded document "${doc.name}" (Format: HTML).`,
        doc.createdById,
        doc.createdBy
      );
    }
  },

  // AUDIT LOGS
  getAuditLogs: (): SystemAuditLog[] => {
    initDb();
    return JSON.parse(localStorage.getItem('pv_audit_logs') || '[]');
  },
  addAuditLog: (action: string, details: string, userId: string, userName: string): SystemAuditLog => {
    initDb();
    const logs = mockDb.getAuditLogs();
    const newLog: SystemAuditLog = {
      id: `log-${uuid()}`,
      timestamp: new Date().toISOString(),
      userId,
      userName,
      action,
      details
    };
    logs.unshift(newLog);
    localStorage.setItem('pv_audit_logs', JSON.stringify(logs.slice(0, 100))); // Keep last 100 logs
    return newLog;
  }
};
