"""Initial schema migration

Revision ID: 9e2d84a377a3
Revises: 
Create Date: 2026-07-15 18:02:16.541243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e2d84a377a3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_activity_logs_timestamp'), 'activity_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_activity_logs_user_id'), 'activity_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_download_logs_generated_document_id'), 'download_logs', ['generated_document_id'], unique=False)
    op.create_index(op.f('ix_download_logs_timestamp'), 'download_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_download_logs_user_id'), 'download_logs', ['user_id'], unique=False)
    op.alter_column('generated_documents', 'download_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.create_index(op.f('ix_generated_documents_created_at'), 'generated_documents', ['created_at'], unique=False)
    op.create_index(op.f('ix_generated_documents_template_id'), 'generated_documents', ['template_id'], unique=False)
    op.create_index(op.f('ix_generated_documents_user_id'), 'generated_documents', ['user_id'], unique=False)
    op.alter_column('html_templates', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'Draft'::character varying"))
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.alter_column('html_templates', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'Draft'::character varying"))
    op.drop_index(op.f('ix_generated_documents_user_id'), table_name='generated_documents')
    op.drop_index(op.f('ix_generated_documents_template_id'), table_name='generated_documents')
    op.drop_index(op.f('ix_generated_documents_created_at'), table_name='generated_documents')
    op.alter_column('generated_documents', 'download_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('ix_download_logs_user_id'), table_name='download_logs')
    op.drop_index(op.f('ix_download_logs_timestamp'), table_name='download_logs')
    op.drop_index(op.f('ix_download_logs_generated_document_id'), table_name='download_logs')
    op.drop_index(op.f('ix_activity_logs_user_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_timestamp'), table_name='activity_logs')
    # ### end Alembic commands ###
